version: '3.8'

services:
#  reverse:
#    image: cloudflare/cloudflared:latest
#    command: tunnel --no-autoupdate run --token eyJhIjoiZjAyYzI3YTY5MDllYzdmMTJiMzQ1NGZhYjIzM2I3MWUiLCJ0IjoiNzUzYTRmZTEtN2VlMS00M2QzLTlkYzUtOTUyYWEwZmYwYWY5IiwicyI6Ik1tUTBOMkpqWmpZdE9XUmlPUzAwT1dVMkxUZzJaR0l0WXpFMll6QmhPVFU1TldJeiJ9
#    restart: always
#    networks:
#      - host

  database:
    image: mongo
    restart: always
    volumes:
      - /share/Container/revolt/revolt_data/data/db:/data/db
    networks:
      - host

  redis:
    image: eqalpha/keydb
    restart: always
    networks:
      - host

  rabbit:
    image: rabbitmq:4
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: rabbituser
      RABBITMQ_DEFAULT_PASS: rabbitpass
    volumes:
      - /share/Container/revolt/revolt_data/data/rabbit:/var/lib/rabbitmq
    networks:
      - host

  minio:
    image: minio/minio
    command: server /data
    volumes:
      - /share/Container/revolt/revolt_data/data/minio:/data
    environment:
      MINIO_ROOT_USER: minioautumn
      MINIO_ROOT_PASSWORD: minioautumn
      MINIO_DOMAIN: minio
    networks:
      host:
        aliases:
          - revolt-uploads.minio
          - attachments.minio
          - avatars.minio
          - backgrounds.minio
          - icons.minio
          - banners.minio
          - emojis.minio
    restart: always

  api:
    image: ghcr.io/revoltchat/server:20250210-1
    depends_on:
      database:
        condition: service_started
      redis:
        condition: service_started
      rabbit:
        condition: service_started
    volumes:
      - /share/Container/revolt/Revolt.toml:/Revolt.toml
    restart: always
    networks:
      - host

  events:
    image: ghcr.io/revoltchat/bonfire:20250210-1
    depends_on:
      database:
        condition: service_started
      redis:
        condition: service_started
    volumes:
      - /share/Container/revolt/Revolt.toml:/Revolt.toml
    restart: always
    networks:
      - host

  web:
    image: ghcr.io/revoltchat/client:master
    environment:
      HOSTNAME: revolt.app-xoure.com
      REVOLT_PUBLIC_URL: https://api.app-xoure.com
    restart: always
    networks:
      - host

  autumn:
    image: ghcr.io/revoltchat/autumn:20250210-1
    depends_on:
      database:
        condition: service_started
      createbuckets:
        condition: service_started
    volumes:
      - /share/Container/revolt/Revolt.toml:/Revolt.toml
    restart: always
    networks:
      - host

  january:
    image: ghcr.io/revoltchat/january:20250210-1
    volumes:
      - /share/Container/revolt/Revolt.toml:/Revolt.toml
    restart: always
    networks:
      - host

  crond:
    image: ghcr.io/revoltchat/crond:20250210-1-debug
    depends_on:
      database:
        condition: service_started
      minio:
        condition: service_started
    volumes:
      - /share/Container/revolt/Revolt.toml:/Revolt.toml
    restart: always
    networks:
      - host

  pushd:
    image: ghcr.io/revoltchat/pushd:20250210-1
    depends_on:
      database:
        condition: service_started
      redis:
        condition: service_started
      rabbit:
        condition: service_started
    volumes:
      - /share/Container/revolt/Revolt.toml:/Revolt.toml
    restart: always
    networks:
      - host

  createbuckets:
    image: minio/mc
    depends_on:
      minio:
        condition: service_started
    entrypoint: >
      /bin/sh -c "
      while ! /usr/bin/mc alias set minio http://minio:9000 minioautumn minioautumn; do
        echo 'Waiting for MinIO...' && sleep 1;
      done;
      /usr/bin/mc mb minio/revolt-uploads || true;
      exit 0;
      "
    networks:
      - host

networks:
  host:
    name: host
    external: true
