version: '3.8'

services:
  database:
    image: mongo
    restart: always
    volumes:
      - /share/Container/revolt/revolt_data/data/db:/data/db
    networks:
      - revolt-network

  redis:
    image: eqalpha/keydb
    restart: always
    networks:
      - revolt-network

  rabbit:
    image: rabbitmq:4
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: rabbituser
      RABBITMQ_DEFAULT_PASS: rabbitpass
    volumes:
      - /share/Container/revolt/revolt_data/data/rabbit:/var/lib/rabbitmq
    networks:
      - revolt-network

  minio:
    image: minio/minio
    command: server /data
    volumes:
      - /share/Container/revolt/revolt_data/data/minio:/data
    environment:
      MINIO_ROOT_USER: minioautumn
      MINIO_ROOT_PASSWORD: minioautumn
      MINIO_DOMAIN: minio
    networks:
      revolt-network:
        aliases:
          - revolt-uploads.minio
          - attachments.minio
          - avatars.minio
          - backgrounds.minio
          - icons.minio
          - banners.minio
          - emojis.minio
    restart: always

  api:
    image: ghcr.io/revoltchat/server:20250210-1
    depends_on:
      database:
        condition: service_started
      redis:
        condition: service_started
      rabbit:
        condition: service_started
    volumes:
      - /share/Container/revolt/Revolt.toml:/Revolt.toml
    restart: always
    networks:
      - revolt-network

  events:
    image: ghcr.io/revoltchat/bonfire:20250210-1
    depends_on:
      database:
        condition: service_started
      redis:
        condition: service_started
    volumes:
      - /share/Container/revolt/Revolt.toml:/Revolt.toml
    restart: always
    networks:
      - revolt-network

  web:
    image: ghcr.io/revoltchat/client:master
    environment:
      HOSTNAME: revolt.xoure.com
      REVOLT_PUBLIC_URL: https://api.revolt.xoure.com
    restart: always
    networks:
      - revolt-network
    ports:
      - 5555:5000

  autumn:
    image: ghcr.io/revoltchat/autumn:20250210-1
    depends_on:
      database:
        condition: service_started
      createbuckets:
        condition: service_started
    volumes:
      - /share/Container/revolt/Revolt.toml:/Revolt.toml
    restart: always
    networks:
      - revolt-network

  january:
    image: ghcr.io/revoltchat/january:20250210-1
    volumes:
      - /share/Container/revolt/Revolt.toml:/Revolt.toml
    restart: always
    networks:
      - revolt-network

  crond:
    image: ghcr.io/revoltchat/crond:20250210-1-debug
    depends_on:
      database:
        condition: service_started
      minio:
        condition: service_started
    volumes:
      - /share/Container/revolt/Revolt.toml:/Revolt.toml
    restart: always
    networks:
      - revolt-network

  pushd:
    image: ghcr.io/revoltchat/pushd:20250210-1
    depends_on:
      database:
        condition: service_started
      redis:
        condition: service_started
      rabbit:
        condition: service_started
    volumes:
      - /share/Container/revolt/Revolt.toml:/Revolt.toml
    restart: always
    networks:
      - revolt-network

  createbuckets:
    image: minio/mc
    depends_on:
      minio:
        condition: service_started
    entrypoint: >
      /bin/sh -c "
      while ! /usr/bin/mc alias set minio http://minio:9000 minioautumn minioautumn; do
        echo 'Waiting for MinIO...' && sleep 1;
      done;
      /usr/bin/mc mb minio/revolt-uploads || true;
      exit 0;
      "
    networks:
      - revolt-network

networks:
  revolt-network:
    name: revolt-network
