services:
  # MongoDB: Database
  database:
    image: docker.io/mongo
    restart: always
    volumes:
      - ./data/db:/data/db

  # Redis: Event message broker & KV store
  redis:
    image: docker.io/eqalpha/keydb
    restart: always

  # RabbitMQ: Internal message broker
  rabbit:
    image: docker.io/rabbitmq:4
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: rabbituser
      RABBITMQ_DEFAULT_PASS: rabbitpass
    volumes:
      - ./data/rabbit:/var/lib/rabbitmq

  # MinIO: S3-compatible storage server
  minio:
    image: docker.io/minio/minio
    command: server /data
    volumes:
      - ./data/minio:/data
    environment:
      MINIO_ROOT_USER: minioautumn
      MINIO_ROOT_PASSWORD: minioautumn
      MINIO_DOMAIN: minio
    networks:
      default:
        aliases:
          - revolt-uploads.minio
          - attachments.minio
          - avatars.minio
          - backgrounds.minio
          - icons.minio
          - banners.minio
          - emojis.minio
    restart: always

  # API server
  api:
    image: ghcr.io/revoltchat/server:20250210-1
    ports:
      - "1234:14702"
    depends_on:
      database:
        condition: service_started
      redis:
        condition: service_started
      rabbit:
        condition: service_started
    volumes:
      - /share/Container/revolt/Revolt.toml:/Revolt.toml
    restart: always

  # Events service
  events:
    image: ghcr.io/revoltchat/bonfire:20250210-1
    ports:
      - "1235:14703"
    depends_on:
      database:
        condition: service_started
      redis:
        condition: service_started
    volumes:
      - /share/Container/revolt/Revolt.toml:/Revolt.toml
    restart: always

  # Web App
  web:
    image: ghcr.io/revoltchat/client:master
    ports:
      - "14702:5000"
    restart: always
    environment:
      HOSTNAME: localhost:1236
      REVOLT_PUBLIC_URL: http://localhost:1234

  # File server
  autumn:
    image: ghcr.io/revoltchat/autumn:20250210-1
    ports:
      - "1237:14704"
    depends_on:
      database:
        condition: service_started
      createbuckets:
        condition: service_started
    volumes:
      - /share/Container/revolt/Revolt.toml:/Revolt.toml
    restart: always

  # Metadata and image proxy
  january:
    image: ghcr.io/revoltchat/january:20250210-1
    ports:
      - "1238:14705"
    volumes:
      - /share/Container/revolt/Revolt.toml:/Revolt.toml
    restart: always

  # Regular task daemon
  crond:
    image: ghcr.io/revoltchat/crond:20250210-1-debug
    depends_on:
      database:
        condition: service_started
      minio:
        condition: service_started
    volumes:
      - /share/Container/revolt/Revolt.toml:/Revolt.toml
    restart: always

  # Push notification daemon
  pushd:
    image: ghcr.io/revoltchat/pushd:20250210-1
    depends_on:
      database:
        condition: service_started
      redis:
        condition: service_started
      rabbit:
        condition: service_started
    volumes:
      - /share/Container/revolt/Revolt.toml:/Revolt.toml
    restart: always

  # Create buckets for MinIO
  createbuckets:
    image: docker.io/minio/mc
    depends_on:
      minio:
        condition: service_started
    entrypoint: >
      /bin/sh -c "
      while ! /usr/bin/mc alias set minio http://minio:9000 minioautumn minioautumn; do
        echo 'Waiting for MinIO...' && sleep 1;
      done;
      /usr/bin/mc mb minio/revolt-uploads || true;
      exit 0;
      "

networks:
  default:
    name: revolt-network
